### ISSUE TITLE
Search / Filter Functionality

### ISSUE THREAD

**Issue by alexkrolick** [wilbertliu/redux-ecosystem#6]
Opening this to discuss the implementation of the search/filter features. Based on the goals in #1 this seems like a pretty meaty task.

-  I think this repo gets quite a lot of hits, so there might be some noticeable costs to maintaining the site if there's a search component.
- The list is relatively small at a few thousand entries, but live filtering JSON on partial text matches would be pretty slow and, more importantly, poorly sorted --- plus there are other things like date ranges and stars to query by. I think it makes sense to use a real search library for this.
  - You could use [Lunr](https://lunrjs.com/guides/getting_started.html) to build a static index and query it. Querying client-side is possible but the index may be fairly large; this would probably be the main reason to use a server-side solution. The nice thing is that the whole site could be static and really cheap to operate.
  - Server-side, you could use Elasticsearch, but it seems like overkill; plus tracking and reindexing would require some ops setup. Algolia (paid search service) might work; reactjs.org uses it for the search box.
  - GraphQL?
- Rather than scraping, it might make sense to implement this entire project inside the main repo and have a publish hook on a CI server that indexes and deploys the app.
  -   - If you write the static site with Gatsby and are using Lunr, you could try [this plugin](https://github.com/andrew-codes/gatsby-plugin-elasticlunr-search) to pull in the search index.

**Comment by alexkrolick** [comment]
Also... aside from initial manual labor to convert it, it would probably be much easier to maintain a search index if the primary repo was converted to one-file-per entry, with markdown frontmatter blocks for metadata. This site could become the primary browse experience instead of Github's markdown view.

(cc @markerikson)

**Comment by markerikson** [comment]
FWIW, I'm happy with the current list repo format, and have no plans to change that.  I _do_ want to point to this new search site on the front page of the list as soon as it's up and running, though.

I generally update the list once a week, on weekends, so the "start scraping" process could easily be manually initiated for now.  No need to worry about automatically kicking off scrapes until later.

I'm sure there's many different ways the scraping/indexing/querying process could be implemented.  I could imagine the scrape results being stored as a simple JSON blob on disk, in an SQLite database, etc.  

My original mockup showed just a single category page or subcategory at a time, so it shouldn't be hard to filter/sort 20-50 entries client-side.

Overall, though, I'd say an initial MVP might be to just show the current categories and entries as they are in the list right now, no filtering or anything.  In fact, this would probably be a good order of operations:

- Client-side UI for the current list contents, no other capabilities
- Add Github/NPM stats collection and display for all entries
- Add sorting
- Add filtering

**Comment by wilbertliu** [comment]
Hello @alexkrolick 👋🏻,

Thank you for opening this issue and discussed the challenge that awaits us, I believe it will be useful when the time arrives to build the search / filter functionality. 🙂

Currently we're at the phase where the product discussion is still ongoing there #1 – _eyeing @markerikson 👀 to reply the latest comment_. And what can we do right now before the product discussion finished is this – I'm making the robot to parse, and @dberget prototype the UI. If you read the last few comments there, we're still arguing whether or not some features will be included or even excluded. You might want to see what I wrote on the filter thing there. And specifically for the search functionality, my attempt to include that on our MVP is to try first and see how slow is that based on the parsed data. We can drop that when it's too slow. But again, since we have an outstanding amount of category and subcategories, having this search functionality upfront will be much better for the people.

But I really appreciate your concern and care though.. 🙌🏻 Even better, you could contribute specifically on the search functionality later if you want! We're more than open for you to do so!

**Comment by wilbertliu** [comment]
Hey @markerikson 👋🏻, 

Could you please see our latest discussion in #1 and give your thoughts there? On my sight we can do the first 3 things that you mentioned above in the MVP, and drop the number 4 (please do read my latest comment #1). And since what you wrote is all about the product roadmap in general, let's discuss in #1 I think? 😀

Thank you! 🙏🏻

**Comment by wilbertliu** [comment]
No response, will close it at the moment.
